spring:
  data:
    mongodb:
      host: ${mongo_host:localhost}
      port: ${mongo_port:27027}
      database: ${mongo_db:testdb}
      username: ${mongo_username:mrxccc}
      password: ${mongo_password:123456}